### ISSUE TITLE
jba is not passing the coverage and junctions arguments to the JaBbA correctly

### ISSUE THREAD

**Issue by pwaltman** [mskilab/JaBbA#18]
Have you forgotten to check in the correct/updated version of the jba executable?

As a test of the install, I installed JaBbA into a new module that I've called "JaBbA_simplified", but it doesn't work with the test data that you provide. Here's the output from that test:

```
waltman@waltman-workstation:~$ cd modules/JaBbA_simplified/
waltman@waltman-workstation:~/modules/JaBbA_simplified$ ls
hydrant.deploy  hydrant.deploy~  JaBbA  run.sh  run.sh~
waltman@waltman-workstation:~/modules/JaBbA_simplified$ ls JaBbA/
configure  configure.ac  DESCRIPTION  inst  JaBbA.pdf  jba  NAMESPACE  R  README.md  rtdocs  srcs  tests
waltman@waltman-workstation:~/modules/JaBbA_simplified$ JaBbA/jba JaBbA/inst/extdata/junctions.vcf JaBbA/inst/extdata/coverage.txt

 _____         ___    _      _____
(___  )       (  _`\ ( )    (  _  )
    | |   _ _ | (_) )| |_   | (_) |
 _  | | /'_` )|  _ <'| '_`\ |  _  |
( )_| |( (_| || (_) )| |_) )| | | |
`\___/'`\__,_)(____/'(_,__/'(_) (_)

(Junction     Balance     Analysis)

JaBbA 2019-01-20 11:08:41: Located junction file JaBbA/inst/extdata/junctions.vcf
JaBbA 2019-01-20 11:08:41: Located coverage file JaBbA/inst/extdata/coverage.txt
JaBbA 2019-01-20 11:08:41: Loading packages ...
JaBbA 2019-01-20 11:08:42: Starting analysis in /ifs/scratch/c2b2/ac_lab/pw2470/devel/mskilab/flows/modules/JaBbA_simplified
JaBbA 2019-01-20 11:08:42: Read in 0 total junctions
JaBbA 2019-01-20 11:08:42: Empty junction input. Will do just one round of optimization.
Error in dt2gr(coverage) :
  Error: Input needs to be data.table or data.frame
Calls: suppressPackageStartupMessages ... withCallingHandlers -> JaBbA -> jabba_stub -> dt2gr
In addition: There were 16 warnings (use warnings() to see them)
Execution halted

```

**Comment by pwaltman** [comment]
checking the code of the jba rscript that's in the repo, it creates an rds file called cmd.args.rds that stores a list with the 2 elements "junctions" and 'coverage', but it doesn't use those in the call to Jabba, i.e. here's the relelvant code snippet from the jba rscript, below. Shouldn't it be passing `opt$coverage` instead of `opt$abu` and `opt$junctions` instead of `junctions$ra`?
```
...
    jmessage('Located junction file ', opt$junctions)
    jmessage('Located coverage file ', opt$coverage)
    jmessage('Loading packages ...')
    writeLines(paste(paste("--", names(opt), " ", sapply(opt, function(x) paste(x, collapse = ",")), sep = "", collapse = " "), sep = ""), paste(opt$outdir, "cmd.args", sep = "/"))
    saveRDS(opt, paste(opt$outdir, "cmd.args.rds", sep = "/"))
    jab = JaBbA(coverage = opt$abu,
                blacklist = opt$blacklist,
                junctions = opt$ra,
                juncs.uf = opt$ra.supp,
                seg = opt$seg,
                cfield = opt$cfield,
                tfield = opt$tfield,
                nseg = opt$nseg,
                hets = opt$hets,
                outdir = opt$outdir,
                subsample = opt$subsample,
                name = opt$name,
                field = opt$field,
                slack = opt$slack,
                loose.penalty.mode = ifelse(opt$boolean, "boolean", "linear"),
                strict = as.logical(opt$strict),
                tilim = opt$tilim,
                ploidy = opt$ploidy,
                purity = opt$purity,
                pp.method = opt$ppmethod,
                verbose = 2,
                mc.cores = opt$cores,
                reiterate = opt$iterate,
                rescue.window = opt$window,
                edgenudge = opt$edgenudge,
                nudge.balanced = opt$nudgebalanced,
                indel = opt$indel,
                all.in = opt$allin,
                use.gurobi = opt$gurobi,
                epgap = opt$epgap,
                max.na = opt$maxna)

```

**Comment by pwaltman** [comment]
UPDATE: after reading the code, I realized that I should set the DEFAULT_GENOME & DEFAULT_BSGENOME environment variables to a seq_lengths file, but I'm still getting the same error, i.e.

```
waltman@waltman-workstation:~/modules/JaBbA_simplified$ export DEFAULT_GENOME=/ifs/scratch/c2b2/ac_lab/shares/resources/Homo_sapiens/GATK/b37/human_g1k_v37_decoy.seq_lengths 
waltman@waltman-workstation:~/modules/JaBbA_simplified$ export DEFAULT_BSGENOME=/ifs/scratch/c2b2/ac_lab/shares/resources/Homo_sapiens/GATK/b37/human_g1k_v37_decoy.seq_lengths 
waltman@waltman-workstation:~/modules/JaBbA_simplified$ !2022
JaBbA/jba JaBbA/inst/extdata/junctions.vcf JaBbA/inst/extdata/coverage.txt

 _____         ___    _      _____
(___  )       (  _`\ ( )    (  _  )
    | |   _ _ | (_) )| |_   | (_) |
 _  | | /'_` )|  _ <'| '_`\ |  _  |
( )_| |( (_| || (_) )| |_) )| | | |
`\___/'`\__,_)(____/'(_,__/'(_) (_)

(Junction     Balance     Analysis)

JaBbA 2019-01-20 11:59:28: Located junction file JaBbA/inst/extdata/junctions.vcf
JaBbA 2019-01-20 11:59:28: Located coverage file JaBbA/inst/extdata/coverage.txt
JaBbA 2019-01-20 11:59:28: Loading packages ...
JaBbA 2019-01-20 11:59:29: Starting analysis in /ifs/scratch/c2b2/ac_lab/pw2470/devel/mskilab/flows/modules/JaBbA_simplified
JaBbA 2019-01-20 11:59:29: Read in 0 total junctions
JaBbA 2019-01-20 11:59:29: Empty junction input. Will do just one round of optimization.
JaBbA 2019-01-20 11:59:29: Importing seg from UCSC format
Error: scanVcf: 'indexname' must be character(1)
  path: JaBbA/inst/extdata/junctions.vcf
In addition: There were 16 warnings (use warnings() to see them)
Execution halted

```

**Comment by mskilab** [comment]
Hi Peter - thanks for pointing this out. indeed jba had drifted away from
the updated JaBbA arguments ... please try now

I also updated so that empty DEFAULT_GENOME or DEFAULT_BSGENOME environment
variable doesn't break ... it just infers from the provided vcf and
coverage files.

If you want to set these variables to custom values - use a path or URL to
a UCSC style .chrom.sizes file or related format

 Let me know if that fixes

**Comment by pwaltman** [comment]
Great, I'll try the new one shortly, but there was one more fix that I had to make to get it running. the vcf(s) that I'm passing in come from svaba, so they use the bam file as the sample identifier in the vcf, and this causes the call to JaBbA() to fail because the default argument for the sample name (opt$name) is set 'tumor'. I've come up with a workaround of editting the jba rscript to allow a 3rd argument to be passed to jba, which is the bam/sample name; and it seems to be working, for the moment at least (it's currently doing the CBS calculation).

**Comment by KathyCat1** [comment]
module load R/4.2.1
jba ~/JaBbA-master/inst/extdata/junctions.vcf  ~/JaBbA-master/inst/extdata/coverage.txt
I still got the same error when I just run test data, how should fix it?  Thanks!                                                                                                                                                 
Starting optimization with CPLEX!
Error in names(x) <- c("xopt", "obj", "status", "extra", "epgap") :
  'names' attribute [5] must be the same length as the vector [1]
Calls: suppressPackageStartupMessages ... ramip_stub -> jbaLP -> balance -> <Anonymous> -> .canonicalize
In addition: There were 17 warnings (use warnings() to see them)
Error in .C("Rcplex_free", PACKAGE = "gGnome") :
  "Rcplex_free" not available for .C() for package "gGnome"
Calls: suppressPackageStartupMessages ... ramip_stub -> jbaLP -> balance -> <Anonymous> -> .C
Execution halted
