### ISSUE TITLE
in ramip_stub function, call 'es = data.table(which(adj!=0, arr.ind=T))' on line 1835 uses base which function, rather than Matrix::which

### ISSUE THREAD

**Issue by pwaltman** [mskilab/JaBbA#20]
the following change resolves the problem. Not sure why it's happening. Perhaps because I'm running the JaBbA function in "debug" mode, i.e. I'm manually calling it within an R shell, and waiting till it crashes. Either way, the explicit call to the Matrix class' version of which will ensure that the correct version is used.

```es = data.table( Matrix::which( adj!=0, arr.ind=T))```

**Comment by pwaltman** [comment]
Same problem occurs on line 2494: Changing
``` G = graph(as.numeric(t(which(tmp.adj != 0, arr.ind=T))), n = length(segstats), directed = T)```

To 
``` G = graph(as.numeric(t(Matrix::which(tmp.adj != 0, arr.ind=T))), n = length(segstats), directed = T)```

resolves the problem

**Comment by xtYao** [comment]
Hi Peter,

Thanks for spotting this. I've pushed the changes to the master branch. Please try again. As you saw we noticed this problem before and added this prefix to many calls of `which`. These two I think slipped through. I'll close this issue for now. Let me know if it works.

Xt
