### ISSUE TITLE
'Rcplex2.o' failed

### ISSUE THREAD

**Issue by mjko1210** [mskilab/JaBbA#26]
Hi,

I added `export CPLEX_DIR=/path/to/your/copy/of/CPLEX_Studio/` to .bashrc.  I was trying to install the package in R but I'm getting following errors while I'm installing the package:
>CPLEX_DIR environment variable, found (CPLEX_DIR=/fh/fast/ha_g/user/mko/CPLEX/cplex), will install CPLEX functionality
>In file included from Rcplex2.c:2:0:
>Rcplex2.h:4:10: fatal error: ilcplex/cplex.h: No such file or directory
 >#include <ilcplex/cplex.h>
 >         ^~~~~~~~~~~~~~~~~
>compilation terminated.
>/app/software/R/3.6.1-foss-2018b/lib/R/etc/Makeconf:167: recipe for target 'Rcplex2.o' failed

I confirmed that I can find `./include/ilcplex/cplex.h` but I wonder where Rcplex2 is located.
Do you have any suggestions for this error?! 

Thanks!

**Comment by imielinski** [comment]
I think you may be one directory too far down?

ie try

CPLEX_DIR=/fh/fast/ha_g/user/mko/CPLEX/

as per installation instructions

NOTE: if CPLEX_DIR is set correctly then $CPLEX_DIR/cplex/include and $CPLEX_DIR/cplex/lib should both exist.

**Comment by mjko1210** [comment]
Thanks, this is working now!
