### ISSUE TITLE
Problem size limits exceeded

### ISSUE THREAD

**Issue by mjko1210** [mskilab/JaBbA#28]
Hi,

I downloaded free edition version for CPLEX Studio. 
However, I ran into an issues while I was running JaBbA. 

`CPLEX environment opened
Rcplex: num variables=3295154 num constraints=3532753
CPLEX Error  1016: Community Edition. Problem size limits exceeded. Purchase at https://ibm.co/2s0wqSa.
Error in Rcplex2(cvec = cvec, Amat = Amat, bvec = consmeta$b, sense = consmeta$sense,  :
  Failed to optimize problem.`

I noticed that free edition is limited to 1000 variable and 1000 constraints. We've applied to IBM academic version but they rejected our application. Is there any way to run this package at this point?

Thanks!

**Comment by mskilab** [comment]
Yes you need the full version of CPLEX or gurobi for most genomes

The problem size is really large.   Are you providing the binned read depth in place of the segment input?  Or is the read depth data really noisy and hypersegmented?

Usually the problem size is about 40-150K




Marcin

________________________________

**Comment by mjko1210** [comment]
Yes. I'm using 10K bin for this run (308,838 bins in total) and my data was from linked reads sequencing. Could you give me little more details on how you define problem size?

**Comment by mjko1210** [comment]
I think 'gurobi' only provide free trial for academic version. How easy it is to run JaBbA with gurobi instead of CPLEX?  Thanks!

**Comment by imielinski** [comment]
The problem size the number of variables + constraints in the MIP

It’s a function of the number of segments and junctions inputted to the graph.

Usually <10,000 segments and <1000 junctions will give you <100K problem size - you have >3M

Sounds like you have either an order of magnitude more segments or junctions than an average highly rearranged cancer genome.  Too many segments can come from noisy read depth data or sensitive segmentation params.     Too many junctions can come from insufficient filtering of false positives

Linked reads have both issues

**Comment by imielinski** [comment]
For gurobi just install the gurobi R package and use the gurobi flag in jba

https://www.gurobi.com/documentation/9.0/refman/ins_the_r_package.html

We haven’t actually tried it in a while, so let us know

Not sure why IBM rejected you but the full version should be available to all academic researchers

https://developer.ibm.com/docloud/blog/2019/07/04/cplex-optimization-studio-for-students-and-academics/

**Comment by xtYao** [comment]
Please see first item in the FAQ.
