### ISSUE TITLE
Using --nseg with sequenza purity/ploidy estimation

### ISSUE THREAD

**Issue by willhooper** [mskilab/JaBbA#29]
Hi,

It looks like supplying an --nseg file while using sequenza purity/ploidy estimation causes an error:

> JaBbA 2020-07-15 14:38:53: loaded hets
JaBbA 2020-07-15 14:39:02: Definining coverage good quality nodes as 10% bases covered by non-NA and non-Inf values in +/-100KB region
JaBbA 2020-07-15 14:39:02: Hard setting 139.765953 Mb of the genome to NA that didn't pass our quality threshold
JaBbA 2020-07-15 14:39:02: Using loess to fit mean to variance relationship in segments with greater than 5 bins
JaBbA 2020-07-15 14:39:03: Using Sequenza to estimate purity ploidy
Error in 1:nrow(segments) : argument of length 0
Calls: suppressPackageStartupMessages ... JaBbA -> jabba_stub -> karyograph_stub -> <Anonymous>
In addition: There were 25 warnings (use warnings() to see them)

Jabba runs to completion when omitting the --nseg argument, or when keeping nseg but using an alternative method for purity/ploidy. I suspect the error might have something to do with this code block assuming that the seqname for the X chromosome is 'X' and not 'chrX':

```
if (exists("nseg") && !is.null(nseg)){
    ## only running w/ diploid autosomes
    ## to avoid situations like HCC1143BL
    good.chr = union(seqnames(nseg %Q% (cn==2)), "X")
    sites = sites[which(chromosome %in% good.chr)]
} else {
     ## only running w/ chr1-22 and X
     sites = sites[which(chromosome %in% seqlevels(ss.tmp))]
}
seg.s1 = sequenza::segment.breaks(sites, breaks = sqz.seg, weighted.mean = FALSE)
```

**Comment by xtYao** [comment]
Thanks Will, this has been fixed.
