### ISSUE TITLE
Error running the test case

### ISSUE THREAD

**Issue by wkljohn** [mskilab/JaBbA#32]
$ jba ${JABBA_PATH}/junctions.vcf ${JABBA_PATH}/coverage.txt

Did not find hets file  setting to NULL
Did not find nseg file  setting to NULL
JaBbA 2020-10-08 13:06:22: Found CPLEX environment in: /software/jabba/CPLEX/

 _____         ___    _      _____
(___  )       (  _`\ ( )    (  _  )
    | |   _ _ | (_) )| |_   | (_) |
 _  | | /'_` )|  _ <'| '_`\ |  _  |
( )_| |( (_| || (_) )| |_) )| | | |
`\___/'`\__,_)(____/'(_,__/'(_) (_)

(Junction     Balance     Analysis)

JaBbA 2020-10-08 13:06:22: Located junction file /home/user/R/x86_64-pc-linux-gnu-library/3.6/JaBbA/extdata//junctions.vcf
JaBbA 2020-10-08 13:06:22: Located coverage file /home/user/R/x86_64-pc-linux-gnu-library/3.6/JaBbA/extdata//coverage.txt
JaBbA 2020-10-08 13:06:22: Loading packages ...
JaBbA 2020-10-08 13:06:23: Starting analysis in /software/jabba
JaBbA 2020-10-08 13:06:24: ALT field format like BND
JaBbA 2020-10-08 13:06:25: Read in 83 total input junctions
JaBbA 2020-10-08 13:06:25: There are 0 tier 1 junctinos; 15 tier 2 junctinos; 68 tier 3 junctinos.
JaBbA 2020-10-08 13:06:25: Read in 26,625 5001bp bins of coverage data across 2 chromosomes
JaBbA 2020-10-08 13:06:25: No segmentation provided, so performing segmentation using CBS
JaBbA 2020-10-08 13:06:25: 7 coverage data points have zero value, adding a tiny value 2.22044604925031e-16 to prevent log error.
JaBbA 2020-10-08 13:06:36: Segmentation finished
JaBbA 2020-10-08 13:06:37: 235 segments produced
JaBbA 2020-10-08 13:06:37: Loaded 15 junctions from the input.
JaBbA 2020-10-08 13:06:39: Found tier field enforcing >=1 CN at 0 junctions
JaBbA 2020-10-08 13:06:39: Removing 0 tier 3 junctions
JaBbA 2020-10-08 13:06:39: 2 INDEL-like isolated events
JaBbA 2020-10-08 13:06:39: 2 INDEL-like isolated junctions mandatorily EXCLUDED in the final model
JaBbA 2020-10-08 13:06:39: Conform the reference sequence length of: seg, coverage, and ra, to be:
        16:90354753
        19:59128983
JaBbA 2020-10-08 13:06:39: Did not find nseg file! Ignore.
JaBbA 2020-10-08 13:06:42: Definining coverage good quality nodes as 10% bases covered by non-NA and non-Inf values in +/-100KB region
JaBbA 2020-10-08 13:06:42: Hard setting 4.825004 Mb of the genome to NA that didn't pass our quality threshold
JaBbA 2020-10-08 13:06:42: Using loess to fit mean to variance relationship in segments with greater than 5 bins
Error in file.exists(het.file) : invalid 'file' argument

maybe should use || instread of | on this line?
if (is.null(hets.gr) | !file.exists(het.file)){

**Comment by xtYao** [comment]
Hi, this should be fixed now https://github.com/mskilab/JaBbA/tree/6df1ad5c332bbdb602ada82e3c949b8f22ee002e
