### ISSUE TITLE
Generate coverage txt file using GRIDSS-PURPLE-LINX

### ISSUE THREAD

**Issue by alhafidzhamdan** [mskilab/JaBbA#37]
Hi there,
I've had some technical issues using fragCounter, and hence DryClean.
I want to use purity/ploidy adjusted, gc-corrected copy number calls by GRIDSS-PURPLE-LINX as I think this should be similar, and I already have this run.
Looking at your coverage.txt file, what is your definition of "ratio" ie last column. I presume it's just ?log2(absolute tumour copy number/absolute normal copy number ?)
I appreciate your  help!
A

**Comment by alhafidzhamdan** [comment]
@mskilab @xtYao anyone?

**Comment by xtYao** [comment]
Hi,

Sorry for the late reply. Yes we have used their pipeline for JaBbA too. Their whole genome coverage is generated from a tool called Cobalt, and with that we have been able to run JaBbA. The "field" argument is the metadata column name of the coverage data on each bin, and it is NOT in log space. For example if you have both coverage for tumor and normal, it should just be their ratio, but before purity/ploidy transformation (just provide the purity and ploidy using the respective arguments) and it will be transformed internally.

Hope this helps! (I will work through the fragCounter issue as soon as I can)
Xiaotong

**Comment by alhafidzhamdan** [comment]
Hi @xtYao, thank you- sorry to pester. I appreciate your time.

I had a look at COBALT docs:

`TUMOR.cobalt.ratio.tsv contains the counts and ratios of the reference and tumor:`
```
Chromosome | Position | ReferenceReadCount | TumorReadCount | ReferenceGCRatio | TumorGCRatio | ReferenceGCDiploidRatio
```
ratio = TumorGCRatio/ReferenceGCRatio? or 
ratio = TumorReadCount/ReferenceReadCount

Which of these columns do you use to calculate the ratio? 

I look forward to eventually be able to use fragCounter. Thank you.

A

**Comment by xtYao** [comment]
I think you can directly use their "ReferenceGCDiploidRatio" as your "field".
