### ISSUE TITLE
Failed install JaBbA package 

### ISSUE THREAD

**Issue by Kingsman-Key** [mskilab/JaBbA#38]
I installed the dependencies of the package, except for the IBM academic initiative software. When i tried to install it, R turns out this 

* installing *source* package 'JaBbA' ...
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

** R
** inst
** byte-compile and prepare package for lazy loading
Warning messages:
1: multiple methods tables found for 'seqinfo<-' 
2: replacing previous import 'GenomicRanges::shift' by 'data.table::shift' when loading 'gGnome' 
3: replacing previous import 'GenomicRanges::score' by 'fishHook::score' when loading 'gGnome' 
4: replacing previous import 'GenomicRanges::seqinfo<-' by 'gTrack::seqinfo<-' when loading 'gGnome' 
5: replacing previous import 'Matrix::%&%' by 'gUtils::%&%' when loading 'gGnome' 
6: replacing previous import 'GenomicRanges::union' by 'igraph::union' when loading 'gGnome' 
7: replacing previous import 'data.table::melt' by 'reshape2::melt' when loading 'gGnome' 
8: multiple methods tables found for '%&%' 
** help
No man pages found in package  'JaBbA' 
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Warning: multiple methods tables found for 'seqinfo<-'
Warning: replacing previous import 'GenomicRanges::shift' by 'data.table::shift' when loading 'gGnome'
Warning: replacing previous import 'GenomicRanges::score' by 'fishHook::score' when loading 'gGnome'
Warning: replacing previous import 'GenomicRanges::seqinfo<-' by 'gTrack::seqinfo<-' when loading 'gGnome'
Warning: replacing previous import 'Matrix::%&%' by 'gUtils::%&%' when loading 'gGnome'
Warning: replacing previous import 'GenomicRanges::union' by 'igraph::union' when loading 'gGnome'
Warning: replacing previous import 'data.table::melt' by 'reshape2::melt' when loading 'gGnome'
Warning: multiple methods tables found for '%&%'
Error: package or namespace load failed for 'JaBbA' in library.dynam(lib, package, package.lib):
 DLL 'JaBbA' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'D:/R/R-3.6.3/library/JaBbA'

I tried the augment devtools::install_github("mskilab/JaBbA"， dependency = TRUE)， but it seems that it's not working. I tried to download the source code to local files and installed it. The same error still occurs.  
My operating system is win10 
This is my session info
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] XVector_0.26.0         GenomeInfoDb_1.22.1    compiler_3.6.3         BiocManager_1.30.10    git2r_0.27.1          
 [6] zlibbioc_1.32.0        bitops_1.0-6           prettyunits_1.1.1      remotes_2.1.1          tools_3.6.3           
[11] testthat_3.0.1         digest_0.6.25          pkgbuild_1.0.8         pkgload_1.1.0          memoise_1.1.0         
[16] lattice_0.20-41        pkgconfig_2.0.3        rlang_0.4.10           igraph_1.2.5           Matrix_1.2-18         
[21] cli_2.2.0              rstudioapi_0.11        curl_4.3               parallel_3.6.3         GenomeInfoDbData_1.2.2
[26] withr_2.4.0            IRanges_2.20.2         desc_1.2.0             fs_1.4.1               S4Vectors_0.24.4      
[31] devtools_2.3.0         stats4_3.6.3           rprojroot_1.3-2        grid_3.6.3             data.table_1.13.0     
[36] glue_1.4.1             R6_2.4.1               processx_3.4.5         fansi_0.4.1            sessioninfo_1.1.1     
[41] callr_3.5.1            magrittr_1.5           backports_1.1.7        ps_1.5.0               ellipsis_0.3.1        
[46] usethis_1.6.1          GenomicRanges_1.38.0   BiocGenerics_0.32.0    assertthat_0.2.1       RCurl_1.98-1.2        
[51] crayon_1.3.4 
Please let me know if you need more information about my computer.

**Comment by xtYao** [comment]
> I installed the dependencies of the package, except for the IBM academic initiative software. When i tried to install it, R turns out this 
> 
> 
> 
> * installing *source* package 'JaBbA' ...
> 
> ** using staged installation
> 
> 
> 
>    **********************************************
> 
>    WARNING: this package has a configure script
> 
>          It probably needs manual configuration
> 
>    **********************************************
> 
> 
> 
> 
> 
> ** R
> 
> ** inst
> 
> ** byte-compile and prepare package for lazy loading
> 
> Warning messages:
> 
> 1: multiple methods tables found for 'seqinfo<-' 
> 
> 2: replacing previous import 'GenomicRanges::shift' by 'data.table::shift' when loading 'gGnome' 
> 
> 3: replacing previous import 'GenomicRanges::score' by 'fishHook::score' when loading 'gGnome' 
> 
> 4: replacing previous import 'GenomicRanges::seqinfo<-' by 'gTrack::seqinfo<-' when loading 'gGnome' 
> 
> 5: replacing previous import 'Matrix::%&%' by 'gUtils::%&%' when loading 'gGnome' 
> 
> 6: replacing previous import 'GenomicRanges::union' by 'igraph::union' when loading 'gGnome' 
> 
> 7: replacing previous import 'data.table::melt' by 'reshape2::melt' when loading 'gGnome' 
> 
> 8: multiple methods tables found for '%&%' 
> 
> ** help
> 
> No man pages found in package  'JaBbA' 
> 
> *** installing help indices
> 
> ** building package indices
> 
> ** testing if installed package can be loaded from temporary location
> 
> Warning: multiple methods tables found for 'seqinfo<-'
> 
> Warning: replacing previous import 'GenomicRanges::shift' by 'data.table::shift' when loading 'gGnome'
> 
> Warning: replacing previous import 'GenomicRanges::score' by 'fishHook::score' when loading 'gGnome'
> 
> Warning: replacing previous import 'GenomicRanges::seqinfo<-' by 'gTrack::seqinfo<-' when loading 'gGnome'
> 
> Warning: replacing previous import 'Matrix::%&%' by 'gUtils::%&%' when loading 'gGnome'
> 
> Warning: replacing previous import 'GenomicRanges::union' by 'igraph::union' when loading 'gGnome'
> 
> Warning: replacing previous import 'data.table::melt' by 'reshape2::melt' when loading 'gGnome'
> 
> Warning: multiple methods tables found for '%&%'
> 
> Error: package or namespace load failed for 'JaBbA' in library.dynam(lib, package, package.lib):
> 
>  DLL 'JaBbA' not found: maybe not installed for this architecture?
> 
> Error: loading failed
> 
> Execution halted
> 
> ERROR: loading failed
> 
> * removing 'D:/R/R-3.6.3/library/JaBbA'
> 
> 
> 
> I tried the augment devtools::install_github("mskilab/JaBbA"， dependency = TRUE)， but it seems that it's not working. I tried to download the source code to local files and installed it. The same error still occurs.  
> 
> My operating system is win10 
> 
> This is my session info
> 
> R version 3.6.3 (2020-02-29)
> 
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> 
> Running under: Windows 10 x64 (build 18363)
> 
> 
> 
> Matrix products: default
> 
> 
> 
> locale:
> 
> [1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
> 
> [3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
> 
> [5] LC_TIME=Chinese (Simplified)_China.936    
> 
> 
> 
> attached base packages:
> 
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> 
> 
> loaded via a namespace (and not attached):
> 
>  [1] XVector_0.26.0         GenomeInfoDb_1.22.1    compiler_3.6.3         BiocManager_1.30.10    git2r_0.27.1          
> 
>  [6] zlibbioc_1.32.0        bitops_1.0-6           prettyunits_1.1.1      remotes_2.1.1          tools_3.6.3           
> 
> [11] testthat_3.0.1         digest_0.6.25          pkgbuild_1.0.8         pkgload_1.1.0          memoise_1.1.0         
> 
> [16] lattice_0.20-41        pkgconfig_2.0.3        rlang_0.4.10           igraph_1.2.5           Matrix_1.2-18         
> 
> [21] cli_2.2.0              rstudioapi_0.11        curl_4.3               parallel_3.6.3         GenomeInfoDbData_1.2.2
> 
> [26] withr_2.4.0            IRanges_2.20.2         desc_1.2.0             fs_1.4.1               S4Vectors_0.24.4      
> 
> [31] devtools_2.3.0         stats4_3.6.3           rprojroot_1.3-2        grid_3.6.3             data.table_1.13.0     
> 
> [36] glue_1.4.1             R6_2.4.1               processx_3.4.5         fansi_0.4.1            sessioninfo_1.1.1     
> 
> [41] callr_3.5.1            magrittr_1.5           backports_1.1.7        ps_1.5.0               ellipsis_0.3.1        
> 
> [46] usethis_1.6.1          GenomicRanges_1.38.0   BiocGenerics_0.32.0    assertthat_0.2.1       RCurl_1.98-1.2        
> 
> [51] crayon_1.3.4 
> 
> Please let me know if you need more information about my computer.

Hi,

We haven't tested on Windows yet, but if DLL is not found that likely means the C code is not compiled properly. Please try on a Linux machine if you can. We will see if there's a solution to this meanwhile.

Thank you,
Xiaotong

**Comment by xtYao** [comment]
Hi,

I just noticed you mention that you did not install CPLEX from IBM. It is a requirement for JaBbA, so please try installing that first and follow the README to set up the correct path to your installation. I'll close this for now, please let me know if after you install CPLEX (there's a free academic license), this error still persists.

Xiaotong
