### ISSUE TITLE
About input hets files

### ISSUE THREAD

**Issue by icelu** [mskilab/JaBbA#45]
The option --hets=HETS seems required since my Jabba runs always failed with the following message:
Checking for hets
Error in gzfile(file, "rb") : cannot open the connection
Calls: suppressPackageStartupMessages ... tryCatchList -> tryCatchOne -> <Anonymous> -> readRDS -> gzfile

The file format in provided hets.txt  is: 
seqnames,start,end,width,strand,alt,ref
16,85065,85065,1,*,85,11
16,85658,85658,1,*,82,11

But according to the document, it should be:
tab delimited hets file output of pileup with fields seqnames, start, end, alt.count.t, ref.count.t, alt.count.n, ref.count.n

Could you please clarify how to prepare this hets file? Thanks.

**Comment by ShaiberAlon** [comment]
Hi @icelu,

Thanks for pointing out this discrepancy. Did you resolve this issue?

You should follow the instructions in the help menu:
```
tab delimited hets file output of pileup with fields seqnames, start, end, alt.count.t, ref.count.t, alt.count.n, ref.count.n
```

(in reality, it actually does not have to be TAB-delimited. Comma or space delimited files would also work well)

I am adding some details below that are for our own reference:
Looking at the test, it looks like the processing of hets in the test is done differently from within jabba.

here is the processing in the test file:
https://github.com/mskilab/JaBbA/blob/4762d9bf4dac2344da5ae4287f16df10cf96f12b/tests/testthat/test_JaBbA.R#L47

So probably just need to fix that and fix the header in the provided example hets file. I will fix and test in a branch.

**Comment by icelu** [comment]
Thank you for the clarifications.
