### ISSUE TITLE
installation with Gurobi not work

### ISSUE THREAD

**Issue by banlangen523** [mskilab/JaBbA#65]
hi, I tried install with Gurobi but failed. I tested gurobi and it could work in my R.
Either by devtools::install() or by install.packages('...v1.1.tar.gz', ...) does not work.
Both gave:
...
* installing *source* package ‘JaBbA’ ...
** using staged installation
CPLEX_DIR environment variable not set, please set (e.g. ~/Path/To/CPLEX_Studio/) prior to installing in order to install JaBbA with CPLEX functionality
** libs
...
** R
** inst
** byte-compile and prepare package for lazy loading
Warning message:
multiple methods tables found for ‘seqinfo<-’ 
** help
No man pages found in package  ‘JaBbA’ 
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Warning: multiple methods tables found for ‘seqinfo<-’
Error: package or namespace load failed for ‘JaBbA’:
 .onLoad failed in loadNamespace() for 'JaBbA', details:
  call: jerror("${CPLEX_DIR}/cplex not found")
  error: JaBbA 2022-03-18 14:48:28: ${CPLEX_DIR}/cplex not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/wangyz/anaconda3/envs/R_4.1/lib/R/library/JaBbA’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmphSVXqF/file6b3c508ffcf3/JaBbA_0.0.0.9000.tar.gz’ had non-zero exit status

could you have a look on this? thank you.

**Comment by zining01** [comment]
Hi, thanks reaching out and sharing your error log!

JaBbA throws an error if the environment variable CPLEX_DIR is not defined - this was appropriate when we supported CPLEX exclusively, but should have been removed for users running JaBbA with Gurobi - sorry! Here is a patch that should address this:
https://github.com/mskilab/JaBbA/tree/gurobi

Could you please try reinstalling from this branch? Please let us know if we can help further!

**Comment by banlangen523** [comment]
great, I have installed it correctly.
